# Generated by Django 3.2.5 on 2021-09-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210902_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventform',
            name='event_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
