# Generated by Django 3.2.5 on 2021-09-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('responsibility', models.CharField(max_length=30)),
                ('appointed_from', models.DateField()),
                ('appointed_till', models.DateField()),
            ],
        ),
    ]
